### ISSUE TITLE
Aliases

### ISSUE THREAD

**Issue by gitcabezon** [yhirose/vscode-filtertext#24]
Filter Text appears to be running a limited version of bash in that it ignores aliases in .bashrc and .bash_profile.

I would like to be able to alias "egrep -Pi --color=auto" to "e" so that I can open a log file, run filter text, and enter "e error" and have it show lines with just "error" in them.

Is this even possible with Filter Text without building a wrapper shell script?

(Apologies if this isn't the right place to submit these types of questions/requests.)

**Comment by yhirose** [comment]
@gitcabezon, thanks for the feedback. According to the following article,  it's very difficult or even impossible to do it.
https://askubuntu.com/questions/98782/how-to-run-an-alias-in-a-shell-script
Sorry about that...
