### ISSUE TITLE
Doesn't work on Windows?

### ISSUE THREAD

**Issue by laggingreflex** [yhirose/vscode-filtertext#6]
Tried with command `'find "something"'`, the file contents didn't change (it did become dirty though ())

**Comment by yhirose** [comment]
@laggingreflex, thanks for the report and sorry for the late reply. I am able to reproduce it, but don't know why 'find' doesn't receive the stdin from the extension.

Interestingly, if we use 'findstr' command (it's almost equivalent to 'find' command, but has more features such as regext.), we get right result.  Also I tried with 'sort' command, and confirmed it worked on my Windows. I just suspect the internal implementation in 'find' command for pipe isn't good.

So I can still say this extension basically works on Windows, and I'll make it close.
Please let me know if you have any thoughts on this.
