### ISSUE TITLE
Pipe support

### ISSUE THREAD

**Issue by zakkhoyt** [yhirose/vscode-filtertext#8]
It would be great to have pipe support, and maybe it already does support it but I don't know the proper syntax. 

On command line I can do something like this:
grep 'curl' text.txt | sed 's/.*https/https/'

In VSCode I can get grep to work by dropping the file argument:
grep 'curl'

however I can't seem to get any output once I pipe it into sed.
grep 'curl' | sed 's/.*https/https/'

**Comment by yhirose** [comment]
@zakkhoyt, it's a very good idea that I could also benefit from. I'll work on it when I have time soon.

**Comment by yhirose** [comment]
@zakkhoyt, the new version comes with the pipe support.

**Comment by zakkhoyt** [comment]
Awesome. In VSCode I see:
v0.0.6 - Pipe support

Thanks for implementing and awesome turn around time.
